### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by Orangeskai** [BianSepang/WeebProject#10]
hi i run this in termux and wsl and always showing like this

2021-03-29 09:56:44,186 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.175:443/TcpFull...
2021-03-29 09:56:46,231 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.175:443/TcpFull complete!
2021-03-29 09:56:46,577 - telethon.network.mtprotosender - INFO - Disconnecting from 91.108.56.175:443/TcpFull...
2021-03-29 09:56:46,578 - telethon.network.mtprotosender - INFO - Disconnection from 91.108.56.175:443/TcpFull complete!
2021-03-29 09:56:46,585 - userbot - INFO - Modules to load: ['admin', 'afk', 'android', 'anime', 'anti_spambot', 'aria', 'chat', 'clone', 'covid', 'direct_links', 'dogbin', 'evaluators', 'fban', 'filemanager', 'filter', 'getmusic', 'github', 'google_drive', 'hash', 'help', 'heroku', 'lastfm', 'locks', 'lyrics', 'mega_downloader', 'memes', 'misc', 'multimemes', 'nekobot', 'nekos_img', 'nhentai', 'notes', 'ocr', 'pmpermit', 'profile', 'purge', 'qrcode', 'remove_bg', 'reverse', 'scrapers', 'screencapture', 'sed', 'snips', 'spam', 'spotifynow', 'ssvideo', 'stickers', 'system_stats', 'telegraph', 'time', 'updater', 'upload_download', 'weather', 'welcomes', 'whois', 'wordcloud', 'www']
2021-03-29 09:56:46,587 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.175:443/TcpFull...
2021-03-29 09:56:46,662 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.175:443/TcpFull complete!
Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbc11f27550>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc11f27550>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/WeebProject/userbot/__main__.py", line 27, in <module>
    imported_module = import_module("userbot.modules." + module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/WeebProject/userbot/modules/aria.py", line 57, in <module>
    aria2.set_global_options({"dir": download_path})
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/api.py", line 666, in set_global_options
    return self.client.change_global_option(client_options) == "OK"
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 1377, in change_global_option
    return self.call(self.CHANGE_GLOBAL_OPTION, [options])
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 261, in call
    return self.res_or_raise(self.post(self.get_payload(method, params, msg_id=msg_id)))
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 360, in post
    return requests.post(self.server, data=payload, timeout=self.timeout).json()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbc11f27550>: Failed to establish a new connection: [Errno 111] Connection refused'))
(venv) root@DESKTOP-G8IQ45D:~/WeebProject# nano config.env
(venv) root@DESKTOP-G8IQ45D:~/WeebProject# sudo bash ./exec.sh -x
2021-03-29 09:57:10,140 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.175:443/TcpFull...
2021-03-29 09:57:11,177 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.175:443/TcpFull complete!
2021-03-29 09:57:11,289 - telethon.network.mtprotosender - INFO - Disconnecting from 91.108.56.175:443/TcpFull...
2021-03-29 09:57:11,290 - telethon.network.mtprotosender - INFO - Disconnection from 91.108.56.175:443/TcpFull complete!
2021-03-29 09:57:11,297 - userbot - INFO - Modules to load: ['admin', 'afk', 'android', 'anime', 'anti_spambot', 'aria', 'chat', 'clone', 'covid', 'direct_links', 'dogbin', 'evaluators', 'fban', 'filemanager', 'filter', 'getmusic', 'github', 'google_drive', 'hash', 'help', 'heroku', 'lastfm', 'locks', 'lyrics', 'mega_downloader', 'memes', 'misc', 'multimemes', 'nekobot', 'nekos_img', 'nhentai', 'notes', 'ocr', 'pmpermit', 'profile', 'purge', 'qrcode', 'remove_bg', 'reverse', 'scrapers', 'screencapture', 'sed', 'snips', 'spam', 'spotifynow', 'ssvideo', 'stickers', 'system_stats', 'telegraph', 'time', 'updater', 'upload_download', 'weather', 'welcomes', 'whois', 'wordcloud', 'www']
2021-03-29 09:57:11,299 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.175:443/TcpFull...
2021-03-29 09:57:11,325 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.175:443/TcpFull complete!
Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5d46b21c70>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d46b21c70>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/WeebProject/userbot/__main__.py", line 27, in <module>
    imported_module = import_module("userbot.modules." + module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/WeebProject/userbot/modules/aria.py", line 57, in <module>
    aria2.set_global_options({"dir": download_path})
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/api.py", line 666, in set_global_options
    return self.client.change_global_option(client_options) == "OK"
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 1377, in change_global_option
    return self.call(self.CHANGE_GLOBAL_OPTION, [options])
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 261, in call
    return self.res_or_raise(self.post(self.get_payload(method, params, msg_id=msg_id)))
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 360, in post
    return requests.post(self.server, data=payload, timeout=self.timeout).json()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5d46b21c70>: Failed to establish a new connection: [Errno 111] Connection refused'))
(venv) root@DESKTOP-G8IQ45D:~/WeebProject# nano config.env
(venv) root@DESKTOP-G8IQ45D:~/WeebProject# sudo bash ./exec.sh -x
2021-03-29 09:57:34,690 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.175:443/TcpFull...
2021-03-29 09:57:34,723 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.175:443/TcpFull complete!
2021-03-29 09:57:35,111 - telethon.network.mtprotosender - INFO - Disconnecting from 91.108.56.175:443/TcpFull...
2021-03-29 09:57:35,113 - telethon.network.mtprotosender - INFO - Disconnection from 91.108.56.175:443/TcpFull complete!
2021-03-29 09:57:35,125 - userbot - INFO - Modules to load: ['admin', 'afk', 'android', 'anime', 'anti_spambot', 'aria', 'chat', 'clone', 'covid', 'direct_links', 'dogbin', 'evaluators', 'fban', 'filemanager', 'filter', 'getmusic', 'github', 'google_drive', 'hash', 'help', 'heroku', 'lastfm', 'locks', 'lyrics', 'mega_downloader', 'memes', 'misc', 'multimemes', 'nekobot', 'nekos_img', 'nhentai', 'notes', 'ocr', 'pmpermit', 'profile', 'purge', 'qrcode', 'remove_bg', 'reverse', 'scrapers', 'screencapture', 'sed', 'snips', 'spam', 'spotifynow', 'ssvideo', 'stickers', 'system_stats', 'telegraph', 'time', 'updater', 'upload_download', 'weather', 'welcomes', 'whois', 'wordcloud', 'www']
2021-03-29 09:57:35,128 - telethon.network.mtprotosender - INFO - Connecting to 91.108.56.175:443/TcpFull...
2021-03-29 09:57:35,155 - telethon.network.mtprotosender - INFO - Connection to 91.108.56.175:443/TcpFull complete!
Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f331b1f4a90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/root/WeebProject/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f331b1f4a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/WeebProject/userbot/__main__.py", line 27, in <module>
    imported_module = import_module("userbot.modules." + module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/WeebProject/userbot/modules/aria.py", line 57, in <module>
    aria2.set_global_options({"dir": download_path})
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/api.py", line 666, in set_global_options
    return self.client.change_global_option(client_options) == "OK"
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 1377, in change_global_option
    return self.call(self.CHANGE_GLOBAL_OPTION, [options])
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 261, in call
    return self.res_or_raise(self.post(self.get_payload(method, params, msg_id=msg_id)))
  File "/root/WeebProject/venv/lib/python3.8/site-packages/aria2p/client.py", line 360, in post
    return requests.post(self.server, data=payload, timeout=self.timeout).json()
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/WeebProject/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f331b1f4a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

and when i install in termux many problem with scipy etc plz help

**Comment by BianSepang** [comment]
Just use Heroku or any other cloud platform, Termux is not  recommended for self hosting this userbot

**Comment by Orangeskai** [comment]
just install a aria and other package just run perfectly :v

**Comment by BianSepang** [comment]
ahh nice
